### ISSUE TITLE
dotnet setup

### ISSUE THREAD

**Issue by giannik** [OpenVidu/openvidu-livekit-tutorials#2]
hello.
I'm interested in the dotnet server side implementation of live kit and found your repos.
https://github.com/OpenVidu/openvidu-livekit-tutorials/tree/master/application-server/dotnet

I assume that to make the demo work you would have to install live kit on a Linux server and connect to it from the dotnet application. Is that correct ?

**Comment by pabloFuente** [comment]
Hello,

The tutorial page is already updated with all the steps required to run the dotnet application. You can check it out here: https://livekit-tutorials.openvidu.io/tutorials/application-server/dotnet/
